name: Build and test 

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:

      # recuperer le code 
      - name: Checkout code
        uses: actions/checkout@v3


      # installer les requirements 
      - name: Install dependencies
        run: pip install -r requirements.txt

      # faire les tests tests avec nosetests
      - name: Run tests with nose
        run: |
          pip install nose
          nosetests

        # Si des erreurs sont trouv√©es, on les ignore pour ne pas faire echouer le workflow
      - name: Lint with Flake8 (ignore errors)
        run: |
          pip install flake8
          flake8 . || true
